"""
Pydantic models for the Clinical Trial Designer environment.
All field names follow the naming contract defined in §5.1–5.4 of the project roadmap.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    SET_PRIMARY_ENDPOINT = "set_primary_endpoint"
    SET_SAMPLE_SIZE = "set_sample_size"
    SET_INCLUSION_CRITERIA = "set_inclusion_criteria"
    SET_EXCLUSION_CRITERIA = "set_exclusion_criteria"
    SET_DOSING_SCHEDULE = "set_dosing_schedule"
    SET_CONTROL_ARM = "set_control_arm"
    SET_RANDOMIZATION_RATIO = "set_randomization_ratio"
    SET_BLINDING = "set_blinding"
    RUN_DOSE_ESCALATION = "run_dose_escalation"
    OBSERVE_SAFETY_SIGNAL = "observe_safety_signal"
    ESTIMATE_EFFECT_SIZE = "estimate_effect_size"
    RUN_INTERIM_ANALYSIS = "run_interim_analysis"
    MODIFY_SAMPLE_SIZE = "modify_sample_size"
    ADD_BIOMARKER_STRATIFICATION = "add_biomarker_stratification"
    SUBMIT_TO_FDA_REVIEW = "submit_to_fda_review"
    REQUEST_PROTOCOL_AMENDMENT = "request_protocol_amendment"
    RUN_PRIMARY_ANALYSIS = "run_primary_analysis"
    SYNTHESIZE_CONCLUSION = "synthesize_conclusion"
    ENROLL_PATIENTS = "enroll_patients"


class TrialAction(BaseModel):
    """Represents a single agent action in the trial design episode."""

    action_type: ActionType
    parameters: dict[str, Any]
    justification: str
    confidence: float = Field(ge=0.0, le=1.0)


class TrialObservation(BaseModel):
    """Observable state returned to the agent after each step.

    Generated by OutputGenerator — noisy, never exposes raw hidden values.
    """

    scenario_description: str
    phase_data: dict[str, Any]  # noisy results from experiments
    resource_status: dict[str, Any]  # budget_remaining, time_remaining,
    # patients_enrolled
    rule_violations: list[str]
    available_actions: list[str]  # valid actions given current prerequisites
    steps_taken: int
    max_steps: int
    hint: str  # only populated at junior difficulty
    done: bool
    reward: float


class TrialState(BaseModel):
    """Episode metadata visible to the training loop.

    Field names follow the §5.4 naming contract.
    """

    episode_id: str
    step_count: int
    difficulty: float
    scenario_id: str
    curriculum_tier: str
    curriculum_stats: dict[str, Any]
    action_diversity: float  # unique actions / total actions
    phase_compliance_rate: float
    is_resolved: bool


class TrialLatentState(BaseModel):
    """Hidden ground-truth parameters — never sent to agent."""

    true_effect_size: float
    true_side_effect_rate: float
    true_responder_population: str
    true_responder_criteria: list[str]  # e.g. ["BRCA1+", "age < 65"]
    true_dose_response: dict[float, float]
    true_mechanism: str
    placebo_response_rate: float
    dropout_rate: float
    site_variability: float
    measurement_noise: float
    budget_remaining: float
    time_remaining_days: int
    patients_enrolled: int
    phase_i_complete: bool
    mtd_identified: bool
    effect_estimated: bool
    protocol_submitted: bool
    interim_complete: bool
    trial_complete: bool
    # Episode tracking (used by rule engine and phase detector)
    episode_phase: str
    action_history: list[str]
    seed: int


class TrialResult(BaseModel):
    """Outcome of a simulated trial."""

    p_value: float
    success: bool  # p_value < alpha
    power: float
    adverse_event_rate: float
    confidence_interval: tuple[float, float]
    failure_reason: str | None  # "budget_exhausted", "time_exhausted", "no_enrollment"


class ScenarioConfig(BaseModel):
    """Scenario-specific configuration parameters."""

    scenario_id: str  # one of the four named IDs
    curriculum_tier: int
    disease_area: str
    effect_size_range: tuple[float, float]
    side_effect_rate_range: tuple[float, float]
    placebo_response_range: tuple[float, float]
    dropout_rate_range: tuple[float, float]
    budget_usd: float
    time_budget_days: int
    min_sample_size: int
    description: str


class RewardBreakdown(BaseModel):
    """Decomposed reward components for a single step."""

    r_validity: float
    r_ordering: float
    r_info_gain: float
    r_efficiency: float
    r_novelty: float
    r_penalty: float
    r_terminal_success: float
    r_terminal_calibration: float

    @property
    def total(self) -> float:
        return sum(
            [
                self.r_validity,
                self.r_ordering,
                self.r_info_gain,
                self.r_efficiency,
                self.r_novelty,
                self.r_penalty,
                self.r_terminal_success,
                self.r_terminal_calibration,
            ]
        )


class EpisodeTranscript(BaseModel):
    """One JSONL record per step — full episode trace for offline analysis."""

    episode_id: str
    step: int
    action: TrialAction
    observation: TrialObservation
    reward_breakdown: dict[str, float]  # each of 8 components
    total_reward: float
    phase_detected: str
    phase_order_correct: bool
    hidden_state_snapshot: TrialLatentState  # for offline debugging only
    timestamp: str
